# Generated by Django 4.0.4 on 2022-05-13 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_first_name_user_last_name_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_on',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(db_column='last_login', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(db_column='middle_name', max_length=20, null=True),
        ),
    ]
