# Generated by Django 4.0.4 on 2023-01-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_last_login_on_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('gender_name', models.CharField(db_column='gender_name', max_length=50)),
            ],
            options={
                'db_table': 'core"."genders',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(db_column='contact', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_id',
            field=models.ForeignKey(db_column='gender_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.gendermodel'),
            preserve_default=False,
        ),
    ]
