# Generated by Django 4.0.4 on 2022-06-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='brand_name', max_length=150)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
            ],
            options={
                'db_table': 'product"."brands',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_column='sku', max_length=12, unique=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_default', models.BooleanField(db_column='is_default', default=False)),
                ('store_price', models.BigIntegerField(db_column='store_price')),
                ('discount', models.IntegerField(db_column='discount', null=True)),
                ('retail_price', models.IntegerField(db_column='retail_price')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.brands')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'db_table': 'product"."product_inventory',
            },
        ),
    ]
