# Generated by Django 4.0.4 on 2022-07-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brands_productinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(db_column='attribute_name', max_length=50)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
            ],
            options={
                'db_table': 'product"."attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('attribute_value', models.CharField(db_column='attribute_id', max_length=30)),
                ('attribute_id', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.attribute')),
                ('product_inv_id', models.ForeignKey(db_column='product_inv_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productinventory')),
            ],
            options={
                'db_table': 'product"."product_attribute_values',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('attribute_id', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.attribute')),
                ('sub_category_id', models.ForeignKey(db_column='sub_category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.subcategory')),
            ],
            options={
                'db_table': 'product"."category_attributes',
            },
        ),
    ]
