# Generated by Django 4.0.4 on 2022-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attribute_productattributevalues_categoryattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalues',
            name='attribute_value',
            field=models.CharField(db_column='attribute_value', max_length=30),
        ),
    ]
