# Generated by Django 4.0.4 on 2022-07-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productattributevalues_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='brand_id',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(db_column='brand_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.brands'),
            preserve_default=False,
        ),
    ]
