# Generated by Django 4.0.4 on 2022-10-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_images_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image', to='product.product'),
        ),
    ]
