# Generated by Django 4.0.4 on 2022-11-20 10:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import product.models.category


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_images_is_active_alter_images_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail_img',
            field=models.ImageField(db_column='thumbnail_img', null=True, upload_to=product.models.category.upload_to),
        ),
        migrations.AddField(
            model_name='product',
            name='price_option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(db_column='price_option'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='images',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='product.product'),
        ),
    ]
