# Generated by Django 4.0.4 on 2022-10-26 19:09

from django.db import migrations, models
import home.models.BannerModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPicture',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('alt_text', models.CharField(db_column='alt_text')),
                ('file_name', models.ImageField(upload_to=home.models.BannerModel.upload_to)),
                ('redirect_url', models.CharField(db_column='redirect_url', max_length=500)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
            ],
            options={
                'db_table': 'core"."banner_images',
            },
        ),
    ]
