# Generated by Django 4.0.4 on 2022-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpicture',
            name='alt_text',
            field=models.CharField(db_column='alt_text', max_length=100),
        ),
    ]
