# Generated by Django 4.0.4 on 2023-01-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bannerpicture_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('num_code', models.SmallIntegerField(db_column='num_code', null=True)),
                ('phone_code', models.IntegerField(db_column='phone_code')),
            ],
            options={
                'db_table': 'core"."country_details',
            },
        ),
    ]
