# Generated by Django 4.0.4 on 2022-10-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_images_is_active_alter_images_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('stock_qty', models.BigIntegerField(db_column='stock_qty')),
                ('statement_reference', models.CharField(db_column='statement_reference', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('product_inventory_id', models.ForeignKey(db_column='product_inventory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productinventory')),
            ],
            options={
                'db_table': 'inventory"."stocks',
            },
        ),
    ]
