# Generated by Django 4.0.4 on 2023-01-01 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('order_qty', models.BigIntegerField(db_column='order_qty')),
                ('ordered_date', models.DateField(auto_now_add=True, db_column='ordered_date')),
                ('payment_method', models.BigIntegerField(db_column='payment_method')),
                ('is_payment_completed', models.BooleanField(db_column='is_payment_completed', default=False)),
                ('created_on', models.DateField(auto_now_add=True, db_column='created_on')),
                ('updated_on', models.DateField(auto_now_add=True, db_column='updated_on')),
                ('delivered_date', models.DateField(auto_now_add=True, db_column='delivered_date')),
                ('ordered_by', models.ForeignKey(db_column='ordered_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('product_inventory_id', models.ForeignKey(db_column='product_inventory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productinventory')),
            ],
            options={
                'db_table': 'inventory"."orders',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cart_qty', models.BigIntegerField(db_column='cart_qty')),
                ('status', models.BooleanField(db_column='status', default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('order_id', models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.ordersmodel')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('product_inventory_id', models.ForeignKey(db_column='product_inventory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productinventory')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory"."cart',
            },
        ),
    ]
